### ISSUE TITLE
error checking

### ISSUE THREAD

**Issue by sethkor** [iafan/cwalk#1]
First, I love this library, I do enormous file copies with this daily.  Thanks for making it.

But I have found a problem when it comes to file limits.

Looking through the code, there are a couple of places where errors are returned, but not checked. 

The scenario is while I'm walking the files with this library, I'm also opening and processing the files.  This leads me to hit the file limit.

In the library this manifests through readDirNames failing.  It returns an err to processPath and processPath detects it and returns it.  However err is never checked in processPath calls

What this means is the library continues to process, ignoring the errors and not reporting the directories it had errors reading.  But it also never passes back an error via Walk to indicate there was a problem walking the file system leading to in consistent results from file walking in terms on number of files walked.

I'm happy to have an attempt and fixing this with a PR if you'll accept it or you may wish to fix yourself.

Cheers
Seth

**Comment by iafan** [comment]
Thanks for writing this up, Seth! Reporting errors makes sense. I think this needs to be done by reporting individual errors via a channel and storing them inside the Walker struct, and then in https://github.com/iafan/cwalk/blob/master/cwalk.go#L121 returning the custom error that has a list of individual errors as a part of its structure.

If all of the above makes sense, you can try implementing this and making a PR.
