### ISSUE TITLE
Inconsistent number of file count

### ISSUE THREAD

**Issue by awsp** [iafan/cwalk#4]
Thank you for the great library.

One thing I notice, when I keep re-running the same program again on the same directory (a node_modules for the testing purposes), I get different file counts at each run.

Also, I receive different file count than the one I get from Windows properties. 
Any ideas? 

PS: I am running on a 8-core machine and SSD.

**Comment by iafan** [comment]
Do you get any errors returned? There was a recent change that introduced error gathering. See #1 for the explanation and related code that was introduced.

Do you get these discrepancies in your own code or in the provided `bin/traversaltime` utility?(see https://github.com/iafan/cwalk/blob/master/bin/traversaltime.go). It can be that the code in the callback function affects the behavior. Try `bin/traversaltime` on your folder and see if the numbers change across multiple runs for both `cwalk` and default `filepath.walk` implementation (this utility will report both).

It can also be some Windows-specific issue, especially with long file paths. Windows has historically had a file path limitation of 260 symbols, and `node_modules` specifically is the case where file paths get bigger than that, introducing all sorts of problems under Windows (inability to check out such a tree from Git, inability to properly install modules, or compile an npm project).

If you see discrepancies in reported numbers when running `bin/traversaltime`, try to run it in some subdirectory and see if the problem persists. If you can isolate the problem to some directory down the tree, check for the file path length.

**Comment by awsp** [comment]
I was using my own code and no errors was returned. 
The program completed successfully. 
But interesting I just got different file count per run. 

Hope I didn't get into some weird race conditions in this code :D
Sample code I was using, I switched to my Macbook Pro and run for another few tests. 
Still get inconsistent results. 
```go
package main

import(
	"fmt"
	"github.com/iafan/cwalk"
	"os"
)

func main() {
	files := scan(os.Args[1])
	fmt.Printf("# of files scanned: %d", len(*files))
}

func scan(dir string) *[]string {
	var files []string

	err := cwalk.Walk(dir, func(root string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		files = append(files, root)
		return nil
	})

	if err != nil {
		panic(err)
	}

	return &files
}
```

### Test result 1
```
/usr/local/Cellar/go/1.12.4/libexec/bin/go build -o /private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui gocui #gosetup
/private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui /Users/awsp/Lab/antd-demo #gosetup
# of files scanned: 29963
Process finished with exit code 0
```

### Test result 2
```
/usr/local/Cellar/go/1.12.4/libexec/bin/go build -o /private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui gocui #gosetup
/private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui /Users/awsp/Lab/antd-demo #gosetup
# of files scanned: 29992
Process finished with exit code 0
```

### Test result 3
```
/usr/local/Cellar/go/1.12.4/libexec/bin/go build -o /private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui gocui #gosetup
/private/var/folders/hw/5_5np1xn7kn_vqw99zt3vlcr0000gn/T/___go_build_gocui /Users/awsp/Lab/antd-demo #gosetup
# of files scanned: 29724
Process finished with exit code 0
```

Here's the result I got from `bin/traversalttime`, the files and directories remained the same. 
```
Running a concurrent version that doesn't follow symlinks with 8 workers and 0s file processing time... done in 93.572825ms
        3779 directories found
        26811 files found
        0 errors found
Running a standard version (single-threaded, doesn't follow symlinks) with 0s file processing time... done in 334.465182ms
        3779 directories found
        26811 files found
        0 errors found

```

### Update: 
Attaching the file count from Finder's inspector. 
<img width="261" alt="Screen Shot 2019-07-29 at 9 08 56 PM" src="https://user-images.githubusercontent.com/2015218/62108219-3436b980-b245-11e9-8046-ef2989c150b8.png">

**Comment by iafan** [comment]
Thanks for providing the additional information. The difference between the number of files on your screenshot and the one provided by `bin/traversaltime` can potentially be attributed to symlinks. Try running `bin/traversaltime -f` and comparing the file counts.

Now, to your original question: the reason you get different numbers in your own code is that you have a data race condition in your callback function, in this line:

```go
files = append(files, root)
```

With `cwalk`, this callback function is executed concurrently from multiple goroutines, so it has to be thread-safe. You can see that the callback function implementation in `bin/traversaltime` uses `atomic.AddInt32(...)` to increment the counter, not a regular increment operation. So you need to implement your list population differently. You can do this with a mutex (https://godoc.org/sync#Mutex), or use https://godoc.org/golang.org/x/sync/syncmap or push the value to a channel and then have a single goroutine to read this channel and append to a slice, or even process the files right within your callback without adding all their names to one slice (depending on what you need to do with these files).

**Comment by awsp** [comment]
Thank you for the explanation!
I can now clearly see where the issue is at. 

I get the same result when running `bin/traversaltime -f` now. 

Looks like I have to implement my own implementation on populating all the files' summary. :D
