### ISSUE TITLE
Please describe differences to MichaelTJones/walk

### ISSUE THREAD

**Issue by hupfdule** [iafan/cwalk#5]
[MichaelTJones/walk](https://github.com/MichaelTJones/walk) seems to be an older implemention with the same purpose as cwalk. It would be nice to know what differentiates both libraries.

I have tried both and found actually no differences in my use case:

- both take the same amount of time (and are much faster than the builtin `filepath.Walk()`).
- both do not prepend the path of the found files with the search path (as opposed to the behaviour of the builtin `filepath.Walk()`) (see also #3)
- both to not sort the output (as opposed to the behaviour of the builtin `filepath.Walk()`).

For the records: I also tried [godirwalk](https://github.com/karrick/godirwalk). But even though the README of godirwalk indicates it would be faster than its competitors and [other comparisons ](https://boyter.org/2018/03/quick-comparison-go-file-walk-implementations/) come to the same conclusion, I found that it is way slower than both, `cwalk` and `MichaelTJones/walk`, in my use case (even though still faster than the builtin `filepath.Walk()`).
Interestingly it didn't even make a difference whether the output is sorted or not.

**Comment by iafan** [comment]
Idk, MichaelTJones/walk seems to have a lot of code borrowed from stdlib, so it's hard to compare. Not sure why this was needed.

CWalk also returns all encountered errors (see #1) while the other library returns the first error encountered (according to their readme). Overall, I'd say you need to try both and see what works best for you.

**Comment by iafan** [comment]
I'll close this as resolved, but let me know if you have further questions.
