### ISSUE TITLE
Changes to support modules

### ISSUE THREAD

**Issue by sethkor** [iafan/cwalk#7]
@iafan I'm wondering if we should do a small amount of work to add support for modules?  Happy to work on it as a PR.

**Comment by iafan** [comment]
@sethkor I understand running `go mod init <...>` is all is needed? Feel free to do a PR.

**Comment by sethkor** [comment]
I think it also involves providing a semantic version for this library too, i.e. v1.0.0.  are you okay with this @iafan ?

**Comment by iafan** [comment]
@sethkor I merged your PR, and also added a v1.0 release. Thanks for the contribution!
